import { Link, useNavigate } from 'react-router-dom';
import { Brain, Mic, BarChart3, Zap, Shield, Users, BookOpen } from 'lucide-react';
import { useAuthStore } from '../store/authStore';
import { Button } from '../components/Button';
import { ScrollFadeIn } from '../components/ScrollFadeIn';
import { AnimatedCounter } from '../components/AnimatedCounter';

const steps = [
  {
    step: '01',
    icon: Brain,
    title: 'Choose Your Interview',
    description:
      'Select your role - Frontend, Backend, Full Stack, DevOps, AI/ML, Gen AI, MLOps, Data Engineer, or Data Scientist - and your difficulty level.',
  },
  {
    step: '02',
    icon: Mic,
    title: 'Speak Your Answers',
    description:
      'Our AI asks real interview questions. Record your voice answers just like a real interview.',
  },
  {
    step: '03',
    icon: BarChart3,
    title: 'Get Instant Feedback',
    description:
      'Receive detailed scoring, feedback, and follow-up questions. Track your improvement over time.',
  },
];

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Questions',
    description:
      'Dynamic questions generated by advanced AI, tailored to your skill level and tech stack.',
  },
  {
    icon: Mic,
    title: 'Voice-Based Answers',
    description:
      'Practice speaking your answers naturally, just like in a real interview setting.',
  },
  {
    icon: BarChart3,
    title: 'Detailed Scoring',
    description: 'Get scored on each answer with specific feedback on what to improve.',
  },
  {
    icon: Zap,
    title: 'Adaptive Follow-ups',
    description: 'AI generates contextual follow-up questions based on your answers.',
  },
  {
    icon: Shield,
    title: 'Multiple Tech Stacks',
    description:
      'Frontend, Backend, Full Stack, DevOps, and Data Science interview tracks.',
  },
  {
    icon: Users,
    title: 'Track Progress',
    description:
      'Review your interview history and watch your scores improve over time.',
  },
];

const stats = [
  { value: 10000, suffix: '+', label: 'Practice Interviews' },
  { value: 95, suffix: '%', label: 'User Satisfaction' },
  { value: 3, suffix: 'x', label: 'Better Interview Performance' },
];

export function LandingPage() {
  const navigate = useNavigate();
  const { token } = useAuthStore();

  return (
    <div className="min-h-screen bg-white text-gray-900 dark:bg-gray-950 dark:text-gray-100">
      <nav className="sticky top-0 z-50 bg-white/90 backdrop-blur border-b border-gray-100 dark:bg-gray-900/90 dark:border-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="h-16 flex items-center justify-between">
            <Link to="/" className="text-2xl font-bold text-gradient">
              IntervuAI
            </Link>
            <div className="flex items-center gap-3 sm:gap-4">
              <button
                onClick={() => navigate('/docs')}
                className="hidden sm:flex items-center gap-1.5 text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white transition-colors"
              >
                <BookOpen className="w-4 h-4" />
                Docs
              </button>
              <button
                onClick={() => navigate('/pricing')}
                className="hidden sm:block text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white transition-colors"
              >
                Pricing
              </button>
              {token ? (
                <Button size="sm" onClick={() => navigate('/dashboard')}>
                  Dashboard
                </Button>
              ) : (
                <>
                  <button
                    onClick={() => navigate('/login')}
                    className="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white transition-colors"
                  >
                    Sign In
                  </button>
                  <Button size="sm" onClick={() => navigate('/register')}>
                    Get Started
                  </Button>
                </>
              )}
            </div>
          </div>
        </div>
      </nav>

      <section className="relative pt-24 pb-20 lg:pt-36 lg:pb-28 overflow-hidden">
        <div className="absolute inset-0 grid-bg opacity-40" />
        <div className="absolute top-1/3 left-1/4 w-[500px] h-[500px] bg-blue-500/10 rounded-full blur-[120px]" />
        <div className="absolute bottom-1/4 right-1/4 w-[400px] h-[400px] bg-indigo-500/10 rounded-full blur-[100px]" />

        <div className="absolute top-40 left-[10%] text-blue-500/20 text-8xl font-mono animate-float select-none hidden lg:block">
          {'{ }'}
        </div>
        <div
          className="absolute bottom-32 right-[10%] text-indigo-500/20 text-7xl font-mono animate-float select-none hidden lg:block"
          style={{ animationDelay: '2s' }}
        >
          {'< />'}
        </div>

        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-100 border border-blue-200 text-blue-700 text-sm font-medium mb-8 dark:bg-blue-900/30 dark:text-blue-300 dark:border-blue-800">
            <Zap className="w-4 h-4" />
            AI-Powered Technical Interview Practice
          </div>

          <h1 className="text-5xl sm:text-6xl lg:text-8xl font-extrabold leading-[1.1] mb-6">
            Ace Your Next
            <span className="block text-gradient animate-shimmer bg-gradient-to-r from-blue-500 via-indigo-500 to-blue-600">
              Tech Interview
            </span>
          </h1>

          <p className="text-lg sm:text-xl text-gray-600 dark:text-gray-300 max-w-2xl mx-auto mb-10 leading-relaxed">
            Practice with an AI interviewer that asks real technical questions, listens to your
            voice answers, and gives instant, detailed feedback. Just like a real interview, but on
            your schedule.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button
              size="lg"
              className="text-lg px-8 py-6 animate-pulse-glow"
              onClick={() => navigate(token ? '/dashboard' : '/register')}
            >
              {token ? 'Go to Dashboard ->' : 'Start Free Interview ->'}
            </Button>
            <button
              onClick={() =>
                document
                  .getElementById('how-it-works')
                  ?.scrollIntoView({ behavior: 'smooth' })
              }
              className="px-8 py-3 text-lg font-semibold text-gray-800 dark:text-gray-100 bg-gray-100 dark:bg-gray-800 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
            >
              See How It Works
            </button>
          </div>

          <p className="text-sm text-gray-500 dark:text-gray-400 mt-6">
            No credit card required | 3 free interviews
          </p>
        </div>
      </section>

      <section id="how-it-works" className="py-24 lg:py-32 relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <ScrollFadeIn className="text-center mb-16">
            <h2 className="text-4xl lg:text-5xl font-bold mb-4">How It Works</h2>
            <p className="text-xl text-gray-600 dark:text-gray-300">
              Three simple steps to interview-ready confidence
            </p>
          </ScrollFadeIn>

          <div className="grid md:grid-cols-3 gap-8">
            {steps.map((item, idx) => {
              const Icon = item.icon;

              return (
                <ScrollFadeIn key={item.step} delay={idx * 150}>
                  <div className="glass-card p-8 text-center group hover:glow-card transition-all duration-300 hover:-translate-y-1">
                    <div className="text-sm font-mono text-blue-600/70 mb-4">{item.step}</div>
                    <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-100 dark:bg-blue-900/30 rounded-2xl mb-6 group-hover:bg-blue-200 dark:group-hover:bg-blue-800/40 transition-colors">
                      <Icon className="w-8 h-8 text-blue-600 dark:text-blue-300" />
                    </div>
                    <h3 className="text-xl font-bold mb-3">{item.title}</h3>
                    <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                      {item.description}
                    </p>
                  </div>
                </ScrollFadeIn>
              );
            })}
          </div>
        </div>
      </section>

      <section className="py-24 lg:py-32 relative">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-blue-500/[0.03] to-transparent" />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <ScrollFadeIn className="text-center mb-16">
            <h2 className="text-4xl lg:text-5xl font-bold mb-4">Why IntervuAI?</h2>
            <p className="text-xl text-gray-600 dark:text-gray-300">
              Everything you need to prepare for technical interviews
            </p>
          </ScrollFadeIn>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, idx) => {
              const Icon = feature.icon;

              return (
                <ScrollFadeIn key={feature.title} delay={idx * 100}>
                  <div className="flex gap-4 p-6 rounded-xl hover:bg-gray-100/80 dark:hover:bg-gray-800/70 transition-all duration-300 group">
                    <div className="flex-shrink-0 w-12 h-12 bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-300 rounded-xl flex items-center justify-center group-hover:bg-blue-200 dark:group-hover:bg-blue-800/40 transition-colors">
                      <Icon className="w-6 h-6" />
                    </div>
                    <div>
                      <h3 className="text-lg font-bold mb-2">{feature.title}</h3>
                      <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                        {feature.description}
                      </p>
                    </div>
                  </div>
                </ScrollFadeIn>
              );
            })}
          </div>
        </div>
      </section>

      <section className="py-20 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-blue-500/10 via-indigo-500/15 to-blue-500/10" />
        <div className="absolute inset-0 grid-bg opacity-20" />
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <ScrollFadeIn>
            <h2 className="text-3xl lg:text-4xl font-bold mb-12">Trusted by Developers</h2>
          </ScrollFadeIn>
          <div className="grid md:grid-cols-3 gap-8">
            {stats.map((item, idx) => (
              <ScrollFadeIn key={item.label} delay={idx * 200}>
                <div>
                  <p className="text-5xl lg:text-6xl font-extrabold text-gradient mb-2">
                    <AnimatedCounter end={item.value} suffix={item.suffix} />
                  </p>
                  <p className="text-gray-600 dark:text-gray-300 text-lg">{item.label}</p>
                </div>
              </ScrollFadeIn>
            ))}
          </div>
        </div>
      </section>

      <section className="py-24 lg:py-32">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <ScrollFadeIn>
            <div className="glass-card p-12 lg:p-16 relative overflow-hidden">
              <div className="absolute inset-0 bg-gradient-to-br from-blue-500/10 via-transparent to-indigo-500/10" />
              <div className="relative">
                <h2 className="text-4xl lg:text-5xl font-bold mb-6">
                  Ready to Crush Your Next Interview?
                </h2>
                <p className="text-xl text-gray-600 dark:text-gray-300 mb-10">
                  Start practicing today with your free interview. No credit card required.
                </p>
                <Button
                  size="lg"
                  className="text-lg px-10 py-6 animate-pulse-glow"
                  onClick={() => navigate(token ? '/dashboard' : '/register')}
                >
                  {token ? 'Go to Dashboard ->' : 'Get Started Free ->'}
                </Button>
              </div>
            </div>
          </ScrollFadeIn>
        </div>
      </section>

      <footer className="border-t border-gray-200 dark:border-gray-800 py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-6">
            <div className="text-2xl font-bold text-gradient">IntervuAI</div>
            <div className="flex items-center gap-6 text-sm text-gray-600 dark:text-gray-300">
              <Link to="/docs" className="hover:text-gray-900 dark:hover:text-white transition-colors">
                Docs
              </Link>
              <Link
                to="/pricing"
                className="hover:text-gray-900 dark:hover:text-white transition-colors"
              >
                Pricing
              </Link>
              <Link
                to="/privacy"
                className="hover:text-gray-900 dark:hover:text-white transition-colors"
              >
                Privacy
              </Link>
              <Link to="/terms" className="hover:text-gray-900 dark:hover:text-white transition-colors">
                Terms
              </Link>
            </div>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              (c) {new Date().getFullYear()} IntervuAI. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
